package DAOinsert;
// Generated 2017-3-24 0:54:17 by Hibernate Tools 5.2.1.Final

/**
 * Mac generated by hbm2java
 */
public class Mac implements java.io.Serializable {

	private String mac;
	private Double rssi;
	private String ts;
	private String ds;
	private String essid0;
	private String essid1;
	private String essid2;
	private String essid3;
	private String essid4;
	private String essid5;
	private String essid6;
	private String timeslot;
	private String lenofstay;
	private String date;
	private String probeId;

	public Mac() {
	}

	public Mac(String mac, String probeId) {
		this.mac = mac;
		this.probeId = probeId;
	}

	public Mac(String mac, Double rssi, String ts, String ds, String essid0, String essid1, String essid2,
			String essid3, String essid4, String essid5, String essid6, String timeslot, String lenofstay, String date,
			String probeId) {
		this.mac = mac;
		this.rssi = rssi;
		this.ts = ts;
		this.ds = ds;
		this.essid0 = essid0;
		this.essid1 = essid1;
		this.essid2 = essid2;
		this.essid3 = essid3;
		this.essid4 = essid4;
		this.essid5 = essid5;
		this.essid6 = essid6;
		this.timeslot = timeslot;
		this.lenofstay = lenofstay;
		this.date = date;
		this.probeId = probeId;
	}

	public String getMac() {
		return this.mac;
	}

	public void setMac(String mac) {
		this.mac = mac;
	}

	public Double getRssi() {
		return this.rssi;
	}

	public void setRssi(Double rssi) {
		this.rssi = rssi;
	}

	public String getTs() {
		return this.ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

	public String getDs() {
		return this.ds;
	}

	public void setDs(String ds) {
		this.ds = ds;
	}

	public String getEssid0() {
		return this.essid0;
	}

	public void setEssid0(String essid0) {
		this.essid0 = essid0;
	}

	public String getEssid1() {
		return this.essid1;
	}

	public void setEssid1(String essid1) {
		this.essid1 = essid1;
	}

	public String getEssid2() {
		return this.essid2;
	}

	public void setEssid2(String essid2) {
		this.essid2 = essid2;
	}

	public String getEssid3() {
		return this.essid3;
	}

	public void setEssid3(String essid3) {
		this.essid3 = essid3;
	}

	public String getEssid4() {
		return this.essid4;
	}

	public void setEssid4(String essid4) {
		this.essid4 = essid4;
	}

	public String getEssid5() {
		return this.essid5;
	}

	public void setEssid5(String essid5) {
		this.essid5 = essid5;
	}

	public String getEssid6() {
		return this.essid6;
	}

	public void setEssid6(String essid6) {
		this.essid6 = essid6;
	}

	public String getTimeslot() {
		return this.timeslot;
	}

	public void setTimeslot(String timeslot) {
		this.timeslot = timeslot;
	}

	public String getLenofstay() {
		return this.lenofstay;
	}

	public void setLenofstay(String lenofstay) {
		this.lenofstay = lenofstay;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getProbeId() {
		return this.probeId;
	}

	public void setProbeId(String probeId) {
		this.probeId = probeId;
	}

}
