package DAOinsert;
// Generated 2017-3-24 0:54:17 by Hibernate Tools 5.2.1.Final

/**
 * Otherinfo generated by hbm2java
 */
public class Otherinfo implements java.io.Serializable {

	private String time;
	private String id;
	private String mmac;
	private String lon;
	private String lat;
	private Integer size;
	private Integer insize;
	private Double inrate;

	public Otherinfo() {
	}

	public Otherinfo(String time) {
		this.time = time;
	}

	public Otherinfo(String time, String id, String mmac, String lon, String lat, Integer size, Integer insize,
			Double inrate) {
		this.time = time;
		this.id = id;
		this.mmac = mmac;
		this.lon = lon;
		this.lat = lat;
		this.size = size;
		this.insize = insize;
		this.inrate = inrate;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getMmac() {
		return this.mmac;
	}

	public void setMmac(String mmac) {
		this.mmac = mmac;
	}

	public String getLon() {
		return this.lon;
	}

	public void setLon(String lon) {
		this.lon = lon;
	}

	public String getLat() {
		return this.lat;
	}

	public void setLat(String lat) {
		this.lat = lat;
	}

	public Integer getSize() {
		return this.size;
	}

	public void setSize(Integer size) {
		this.size = size;
	}

	public Integer getInsize() {
		return this.insize;
	}

	public void setInsize(Integer insize) {
		this.insize = insize;
	}

	public Double getInrate() {
		return this.inrate;
	}

	public void setInrate(Double inrate) {
		this.inrate = inrate;
	}

}
