package DAOinsert;
// Generated 2017-3-24 0:54:17 by Hibernate Tools 5.2.1.Final

/**
 * Timeslot generated by hbm2java
 */
public class Timeslot implements java.io.Serializable {

	private TimeslotId id;

	public Timeslot() {
	}

	public Timeslot(TimeslotId id) {
		this.id = id;
	}

	public TimeslotId getId() {
		return this.id;
	}

	public void setId(TimeslotId id) {
		this.id = id;
	}

}
