package DAOinsert;
// Generated 2017-3-24 0:54:17 by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * TimeslotId generated by hbm2java
 */
public class TimeslotId implements java.io.Serializable {

	private String mac;
	private String timeslot;
	private Date date;

	public TimeslotId() {
	}

	public TimeslotId(String mac, String timeslot, Date date) {
		this.mac = mac;
		this.timeslot = timeslot;
		this.date = date;
	}

	public String getMac() {
		return this.mac;
	}

	public void setMac(String mac) {
		this.mac = mac;
	}

	public String getTimeslot() {
		return this.timeslot;
	}

	public void setTimeslot(String timeslot) {
		this.timeslot = timeslot;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TimeslotId))
			return false;
		TimeslotId castOther = (TimeslotId) other;

		return ((this.getMac() == castOther.getMac())
				|| (this.getMac() != null && castOther.getMac() != null && this.getMac().equals(castOther.getMac())))
				&& ((this.getTimeslot() == castOther.getTimeslot()) || (this.getTimeslot() != null
						&& castOther.getTimeslot() != null && this.getTimeslot().equals(castOther.getTimeslot())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMac() == null ? 0 : this.getMac().hashCode());
		result = 37 * result + (getTimeslot() == null ? 0 : this.getTimeslot().hashCode());
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		return result;
	}

}
